In [2]:
import numpy as np

In [3]:
# arange function
arr = np.arange(0,21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [4]:
# zeros function
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
# ones function
arr2 = np.ones(10)
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
# full function
arr3 = np.full(10,3.14)
arr3

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [7]:
# Adding step value
arr = np.arange(0,50,4)
arr


array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [8]:
# adding matrix inside arange using reshape function
arr = np.arange(0,9).reshape(3,3)
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## The difference btwn list and array. 
## when we are dealing with array we can use only same type of elements where as list can contain any dataype
## list computation will take more time as array deals with homogeneous data
## Array is Used only for storing similar datatype

In [9]:
# converting core list to numpy Array
lst = list(range(0,10))        # explicit list creation
l2 = [x for x in range(0,10)]  # list comprehension
l2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
l3 = [str(x) for x in l2]      # converting int to str
l3

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [11]:
l4 = [x**2 for x in l2]        # squaring l2
l4

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [12]:
# arr?

## Array Library

In [13]:
import array as a
ar = a.array('i',l2) # 'i' is dtype which represents integer
ar1 = a.array('i',[x**2 for x in l2])
ar1

array('i', [0, 1, 4, 9, 16, 25, 36, 49, 64, 81])

In [14]:
nparr = np.array([x+3 for x in l2])
nparr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
# explicitly telling to store dtype as float
nparr1 = np.array([x for x in l2],dtype=float) # same change float to str to make string data type
nparr1 

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [16]:
nparr2 = np.float64([x for x in l2])
nparr2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [17]:
# 2-D lsit or Nested list
l2d = [range(i,i+4) for i in [1,4,5]]
np.array(l2d)

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [18]:
np.zeros([2,2],dtype=int) 

array([[0, 0],
       [0, 0]])

In [19]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((3,2),dtype=str)

array([['1', '1'],
       ['1', '1'],
       ['1', '1']], dtype='<U1')

In [21]:
nparr3 = np.zeros((10,10))
nparr3[1:-1,8:-1]=1
nparr3[1:-1,7:-1]=1
nparr3[1:-1,6:-1]=1
nparr3[1:-1,5:-1]=1
nparr3[1:-1,4:-1]=1
nparr3[1:-1,3:-1]=1
nparr3[1:-1,2:-1]=1
nparr3[1:-1,1:-1]=1
nparr3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
nparr3[1:9,1:9]=1
nparr3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
arr = np.full((3,3),3.14)
arr

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [24]:
arr = np.ones((3,3))
arr[:]=3.14
arr

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [25]:
# eye() function for identity matrix
# np.eye?

In [26]:
arr5 = np.eye(7)
arr5

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [27]:
arr7 = np.matrix.transpose(arr5)
arr7

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [28]:
arr8 = np.full((6,6),64)
arr8

array([[64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64]])

## Linspace - Lineraly spaced elements

In [29]:
np.linspace(0,1,5) #starting val , ending val , no. of elements

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [30]:
np.linspace(15,20,20)

array([15.        , 15.26315789, 15.52631579, 15.78947368, 16.05263158,
       16.31578947, 16.57894737, 16.84210526, 17.10526316, 17.36842105,
       17.63157895, 17.89473684, 18.15789474, 18.42105263, 18.68421053,
       18.94736842, 19.21052632, 19.47368421, 19.73684211, 20.        ])

In [31]:
# Random Function - returns value between 0-1
np.random.random((3,3))

array([[0.19028368, 0.09321187, 0.37169651],
       [0.34994521, 0.90533829, 0.18291539],
       [0.71817553, 0.79857073, 0.04185484]])

In [32]:
np.random.normal?

Signature: np.random.normal(loc=0.0, scale=1.0, size=None)
Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

.. note::
    New code should use the `~numpy.random.Generator.normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width")

In [33]:
np.random.normal(0,1,10) #values with mean 0 and std 1


array([-1.07571682,  0.12403465, -0.58391586, -1.63748959,  0.42156082,
       -0.26624043, -0.57520494, -1.44410234,  0.17058618, -0.90756945])

In [34]:
np.random.normal(0,1,(4,5))

array([[ 0.52737283,  1.28045058, -1.57533496, -0.02315965, -0.28720939],
       [ 0.1845334 ,  0.41473695, -0.33470937, -1.0752384 ,  0.32286058],
       [ 0.06870641, -1.43600224, -1.30828955,  1.20618381, -1.9752695 ],
       [ 2.28835415,  0.03463261, -0.03005007, -0.74623412,  0.17998002]])

In [35]:
np.random.randint(50,100,30)

array([67, 88, 58, 63, 82, 76, 95, 78, 52, 91, 81, 85, 69, 69, 59, 95, 63,
       68, 90, 86, 97, 64, 62, 54, 81, 79, 62, 54, 83, 93], dtype=int32)

In [36]:
np.random.randn?


Signature: np.random.randn(*args)
Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned 

### Operations on Numpy Array

In [37]:
arr9 = np.random.randint(10,100,(20,2))
arr9

array([[91, 99],
       [88, 76],
       [41, 48],
       [17, 28],
       [93, 38],
       [53, 38],
       [87, 50],
       [50, 98],
       [17, 90],
       [42, 94],
       [25, 26],
       [94, 84],
       [94, 49],
       [72, 60],
       [97, 46],
       [69, 85],
       [86, 98],
       [39, 12],
       [17, 97],
       [74, 61]], dtype=int32)

In [38]:
arr9.ndim # to check number of dimension of an array

2

In [39]:
arr9.size # to check the size of an array

40

In [40]:
arr9.shape # to check the shape inclusive of both dimension and size

(20, 2)

In [41]:
arr9.dtype # returns datatype of an array

dtype('int32')

### Array Indexing

In [42]:
np.random.seed(101)
ar = np.random.randint(1,10,10)
ar

array([2, 7, 8, 9, 5, 9, 6, 1, 6, 9], dtype=int32)

In [43]:
ar[:4]

array([2, 7, 8, 9], dtype=int32)

In [44]:
ar[-1]

np.int32(9)

In [45]:
ar[5]

np.int32(9)

In [46]:
ar[1]=45
ar

array([ 2, 45,  8,  9,  5,  9,  6,  1,  6,  9], dtype=int32)

### 2-D Array Slicing and Indexing

In [47]:
np.random.seed(100)
arr0 = np.arange(0,25).reshape(5,5)
arr0

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
arr0[0:3,1:3]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [49]:
arr0[0,1]

np.int64(1)

In [50]:
arr0[0:3,1]

array([ 1,  6, 11])

In [51]:
arr0[:3,:3]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [52]:
arr0[2::-1,3::-1]

array([[13, 12, 11, 10],
       [ 8,  7,  6,  5],
       [ 3,  2,  1,  0]])

In [53]:
arr0[2:,3:]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [54]:
arr0[2::2,3::2]

array([[13],
       [23]])

### Shallow Copy and Deep Copy

In [55]:
arr0

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [56]:
# Shallow Copy
ar0 = arr0[2:5,2:5]
ar0

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [57]:
ar0[2,2]=122
ar0

array([[ 12,  13,  14],
       [ 17,  18,  19],
       [ 22,  23, 122]])

In [58]:
arr0 # here ar0 is not a copy of arr0 , it just creates a view and it directs all the changes to the original matrix

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23, 122]])

In [59]:
# Deep Copy
ar1 = arr0[2:5,2:5].copy()
ar1

array([[ 12,  13,  14],
       [ 17,  18,  19],
       [ 22,  23, 122]])

In [60]:
ar1[2,2]=24
ar1

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [61]:
arr0 # here we use .copy() func as to create a copy for the matrix and the changes done in ar1 will not reflect to arr0 and vice-versa 

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23, 122]])

In [62]:
# convert 1:3 matrix in 3:1 matrix using reshape function
arrrr = np.arange(3)
arrrr.reshape(3,1)


array([[0],
       [1],
       [2]])

In [63]:
# convert 1:4 into 2:2 matrix
arrrr = np.arange(16)
reshape = arrrr.reshape(4,4)  #1-D to 2-D
reshape.reshape(1,16)    # conversion of 2-D matrix into 1-D matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [64]:
# returning flat array from 2-D by ravel() func and flatten() func 
ar.ravel?
reshape.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Docstring:
a.ravel([order])

Return a flattened array.

Refer to `numpy.ravel` for full documentation.

See Also
--------
numpy.ravel : equivalent function

ndarray.flat : a flat iterator on the array.
Type:      builtin_function_or_method

In [65]:
# ar.flatten?
flatten = reshape.flatten()

In [66]:
# newaxis keyword instead of reshape can be used
flatten[:,np.newaxis]

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

### Concatenation 

In [67]:
# np.concatenate?

# 1-D array cannot be concated with the 2-D array if u want to do it use .reshape() func or use [[array]] to make it 2-D

In [68]:
np.concatenate([ar0,ar1])  # the elements are added to the row

array([[ 12,  13,  14],
       [ 17,  18,  19],
       [ 22,  23, 122],
       [ 12,  13,  14],
       [ 17,  18,  19],
       [ 22,  23,  24]])

In [69]:
np.concatenate([ar0,ar1],axis=1)  # the elements are added to the column

# axis is to specify row or column

array([[ 12,  13,  14,  12,  13,  14],
       [ 17,  18,  19,  17,  18,  19],
       [ 22,  23, 122,  22,  23,  24]])

In [70]:
ar3=np.array([1,2,3,4,5,6]).reshape(2,3)
ar3

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
ar4=np.array([1,2,3,4,5,6,7,8]).reshape(2,4)
ar4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [72]:
np.concatenate([ar3,ar4],axis=1)

array([[1, 2, 3, 1, 2, 3, 4],
       [4, 5, 6, 5, 6, 7, 8]])

## HStack and VStack

In [73]:
# H-Stack and V-Stack
# np.vstack?
# np.hstack?

In [74]:
x=np.array([[1,2,3],[4,5,6]])
arrrrr = np.array([7,8,9])
ar90 = np.array([[1,2],[3,4]])
ar09 = np.array((1,2,3,4,5))

In [75]:
np.vstack([x,arrrrr])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
np.vstack([arrrrr,x])

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [77]:
np.hstack([x,ar90])

array([[1, 2, 3, 1, 2],
       [4, 5, 6, 3, 4]])

## Split , Vsplit and Hsplit

In [78]:
#np.vsplit?
#np.hsplit?
#np.split?

In [79]:
x
ar89 = np.array((1,2,3,4,5,6))

In [80]:
np.split(ar89,(1,4,5),axis=0) # default split uses vsplit method and 0 is for column and 1 is for row
 # here it returns [:1],[1:4],[4:5],[5:]

[array([1]), array([2, 3, 4]), array([5]), array([6])]

In [81]:
np.vsplit(x,[1,2])

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int64)]

In [82]:
np.hsplit(x,[2,2])
# it return [:1],[1:2],[2:]

[array([[1, 2],
        [4, 5]]),
 array([], shape=(2, 0), dtype=int64),
 array([[3],
        [6]])]

## Universal Functions

In [83]:
ar101 = np.array([[1,2,3],[-4,5,6],[7,-8,9]])
np.sum(ar101)

np.int64(21)

In [84]:
np.sum(ar101,axis=1)

array([6, 7, 8])

In [85]:
np.sum(ar101,axis=0)

array([ 4, -1, 18])

In [86]:
np.std(ar101)

np.float64(5.120763831912405)

In [87]:
np.prod(ar101)

np.int64(362880)

In [88]:
np.var(ar101)

np.float64(26.222222222222218)

In [89]:
np.abs(ar101)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
np.argmax(ar101)

np.int64(8)

In [91]:
np.argmin(ar101)

np.int64(7)

In [92]:
np.argmax(ar101,axis=0)

array([2, 1, 2])

In [93]:
np.argmin(ar101,axis=0)

array([1, 2, 0])

In [94]:
np.argmax(ar101,axis=1)

array([2, 2, 2])

In [95]:
np.argmin(ar101,axis=1)

array([0, 0, 1])

In [96]:
np.median(ar101)

np.float64(3.0)

In [127]:
# np.all?
np.all(ar101,axis=0)

array([ True,  True,  True])

## NUMPY EXERCISE 1


In [97]:
# import numpy
import numpy as np

In [98]:
# 2.Create an array of 10 zeros
np.zeros((1,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [99]:
# 3.Create an array of 10 ones
np.ones((1,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [100]:
# 4.Create an array of the integers from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [101]:
# 5.Create an array of all the even integers from 10 to 50 
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [102]:
# 6.Create a 3x3 matrix with values ranging from 0 to 8 
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [103]:
# 7. Create a 3x3 identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [104]:
# 8. use NumPy to generate a random number between 0 to 1
np.random.randint(0,2,1)


array([0], dtype=int32)

In [105]:
# 9. Use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution
np.random.standard_normal(25)


array([-0.89325872,  1.7382604 , -1.17970327,  0.08857118, -0.36377559,
       -0.39830003, -0.23471518, -1.43973704,  0.4328165 ,  2.30447259,
       -0.12263538,  0.01545931,  0.26601635, -0.11379467,  1.01106614,
       -1.44077118,  0.98056914,  1.37699631, -0.23028509,  0.48092412,
       -1.26691058,  0.27100509,  2.14076322,  0.47536904,  0.24652489])

In [106]:
# 10. Create a matrix of 10x10 matrix of linearly spaced elements from 0.01 to 1
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [128]:
# 11. Create an array of 20 linearly spaced points between 0 and 1
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [130]:
# 12.Create a 5x5 matrix as  
ar1001 = np.array([[ 1,  2,  3,  4,  5], 
       [ 6,  7,  8,  9, 10], 
       [11, 12, 13, 14, 15], 
       [16, 17, 18, 19, 20], 
       [21, 22, 23, 24, 25]]) 
ar1001

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [133]:
# 12.a find following using slicing 
#  array([[12, 13, 14, 15], 
#         [17, 18, 19, 20], 
#         [22, 23, 24, 25]])
ar1001[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [136]:
# 12.b Find using Slicing - 20
ar1001[3:4,-1]

array([20])

In [138]:
# 12.c   array([[ 2], 
             #  [ 7], 
             #  [12]]) 
ar1001[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [142]:
# 12.d array([21, 22, 23, 24, 25])
ar1001[4]

array([21, 22, 23, 24, 25])

In [143]:
# 12.e array([[16, 17, 18, 19, 20], 
            # [21, 22, 23, 24, 25]])
ar1001[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [144]:
# 13. Get sum of all values in matrix 
np.sum(ar1001)

np.int64(325)

In [146]:
# 14. Get sum of all the columns in matrix
np.sum(ar1001,axis=0)

array([55, 60, 65, 70, 75])

In [148]:
# 15. Get Standard deviation , varience , minimum, maximum from matrix row wise
np.std(ar1001,axis=1)

array([1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356])

In [149]:
np.var(ar1001,axis=1)

array([2., 2., 2., 2., 2.])

In [153]:
np.min(ar1001,axis=1)

array([ 1,  6, 11, 16, 21])

In [154]:
np.max(ar1001,axis=1)

array([ 5, 10, 15, 20, 25])

In [179]:
# 16. create 2 d matrix with all border values nan and other values as 1
a = np.full((6,6),np.nan)
a[1:5,1:5]=1
a


array([[nan, nan, nan, nan, nan, nan],
       [nan,  1.,  1.,  1.,  1., nan],
       [nan,  1.,  1.,  1.,  1., nan],
       [nan,  1.,  1.,  1.,  1., nan],
       [nan,  1.,  1.,  1.,  1., nan],
       [nan, nan, nan, nan, nan, nan]])

## NUMPY EXERCISE 2

In [107]:
# 1. create 1-D , 2-D , 3-D numpy array
ar1=np.array([2,3,4,5])
ar1

array([2, 3, 4, 5])

In [108]:
np.random.seed(1)
ar2=np.arange(0,9).reshape(3,3)
ar2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [109]:
np.random.seed(2)
ar3=np.arange(0,27).reshape(3,3,3)
ar3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [110]:
# 2. Print data type of array.
ar3.dtype

dtype('int64')

In [111]:
# 3. Print shape and dimensions of all the three different array.
ar1.shape 

(4,)

In [112]:
ar2.shape

(3, 3)

In [113]:
ar3.shape

(3, 3, 3)

In [114]:
ar1.ndim

1

In [115]:
ar2.ndim

2

In [116]:
ar3.ndim

3

In [117]:
# 4. Create another 1-D array of 12 elements filled with zero
ar4 = np.zeros(12)
ar4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [118]:
# 5. Create another 2-D array elements filled with ones.
ar5 = np.ones((2,10))
ar5

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [119]:
# 6. Create a 1-D array known as Maths Marks out of 100 having 20 elements.
np.random.seed(102)
Maths_Marks = np.random.randint(0,100,20)
Maths_Marks

array([ 0, 78, 66, 73, 72, 45, 72, 73, 79,  7,  4, 38, 82, 55,  3, 96,  0,
       80, 71, 25], dtype=int32)

In [120]:
np.eye(4,4)+4

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

#### 

In [121]:
arrr = [1,2,3,4,5,6,7,8,9,0]
arrr[::-2]


[0, 8, 6, 4, 2]

In [122]:
mat1 = np.ones((9,9))
mat1[::2,::2]=0
mat1[1::2,1::2]=0
mat1

array([[0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0.]])