In [8]:
import numpy as np

In [9]:
# arange function
arr = np.arange(0,21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [10]:
# zeros function
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
# ones function
arr2 = np.ones(10)
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
# full function
arr3 = np.full(10,3.14)
arr3

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [13]:
# Adding step value
arr = np.arange(0,50,4)
arr


array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [14]:
# adding matrix inside arange using reshape function
arr = np.arange(0,9).reshape(3,3)
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## The difference btwn list and array. 
## when we are dealing with array we can use only same type of elements where as list can contain any dataype
## list computation will take more time as array deals with homogeneous data
## Array is Used only for storing similar datatype

In [15]:
# converting core list to numpy Array
lst = list(range(0,10))        # explicit list creation
l2 = [x for x in range(0,10)]  # list comprehension
l2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
l3 = [str(x) for x in l2]      # converting int to str
l3

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [17]:
l4 = [x**2 for x in l2]        # squaring l2
l4

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [18]:
# arr?

## Array Library

In [19]:
import array as a
ar = a.array('i',l2) # 'i' is dtype which represents integer
ar1 = a.array('i',[x**2 for x in l2])
ar1

array('i', [0, 1, 4, 9, 16, 25, 36, 49, 64, 81])

In [20]:
nparr = np.array([x+3 for x in l2])
nparr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
# explicitly telling to store dtype as float
nparr1 = np.array([x for x in l2],dtype=float) # same change float to str to make string data type
nparr1 

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [22]:
nparr2 = np.float64([x for x in l2])
nparr2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [23]:
# 2-D lsit or Nested list
l2d = [range(i,i+4) for i in [1,4,5]]
np.array(l2d)

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [24]:
np.zeros([2,2],dtype=int) 

array([[0, 0],
       [0, 0]])

In [25]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.ones((3,2),dtype=str)

array([['1', '1'],
       ['1', '1'],
       ['1', '1']], dtype='<U1')

In [27]:
nparr3 = np.zeros((10,10))
nparr3[1:-1,8:-1]=1
nparr3[1:-1,7:-1]=1
nparr3[1:-1,6:-1]=1
nparr3[1:-1,5:-1]=1
nparr3[1:-1,4:-1]=1
nparr3[1:-1,3:-1]=1
nparr3[1:-1,2:-1]=1
nparr3[1:-1,1:-1]=1
nparr3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
nparr3[1:9,1:9]=1
nparr3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
arr = np.full((3,3),3.14)
arr

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [30]:
arr = np.ones((3,3))
arr[:]=3.14
arr

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [31]:
# eye() function for identity matrix
# np.eye?

In [32]:
arr5 = np.eye(7)
arr5

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [33]:
arr7 = np.matrix.transpose(arr5)
arr7

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [34]:
arr8 = np.full((6,6),64)
arr8

array([[64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64]])

## Linspace - Lineraly spaced elements

In [35]:
np.linspace(0,1,5) #starting val , ending val , no. of elements

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [36]:
np.linspace(15,20,20)

array([15.        , 15.26315789, 15.52631579, 15.78947368, 16.05263158,
       16.31578947, 16.57894737, 16.84210526, 17.10526316, 17.36842105,
       17.63157895, 17.89473684, 18.15789474, 18.42105263, 18.68421053,
       18.94736842, 19.21052632, 19.47368421, 19.73684211, 20.        ])

In [37]:
# Random Function - returns value between 0-1
np.random.random((3,3))

array([[0.42339034, 0.98587357, 0.59798284],
       [0.73592939, 0.18921072, 0.28494333],
       [0.9646295 , 0.96270611, 0.25989441]])

In [38]:
# np.random.normal?

In [39]:
np.random.normal(0,1,10) #values with mean 0 and std 1


array([-0.40246399, -1.77477776,  0.64394213,  0.69434178,  0.99136842,
        0.02125875,  0.82649941, -0.09130378, -1.62405925, -1.07728141])

In [40]:
np.random.normal(0,1,(4,5))

array([[-1.08083324, -0.19172142, -0.75627602, -0.73152675, -0.52489821],
       [ 0.09638259, -0.74489018,  0.50453025, -1.25512126,  1.63685963],
       [-0.19538311, -2.64984572,  1.44527247, -0.1064697 , -0.21204194],
       [-0.65074902, -0.81256837, -0.92951872, -0.23889738, -1.19768235]])

In [41]:
np.random.randint(50,100,30)

array([76, 67, 86, 65, 94, 65, 67, 84, 63, 94, 91, 84, 65, 70, 53, 54, 53,
       59, 72, 77, 75, 94, 86, 96, 99, 58, 67, 74, 86, 71], dtype=int32)

In [42]:
# np.random.randn?


## Operations on Numpy Array

In [43]:
arr9 = np.random.randint(10,100,(20,2))
arr9

array([[59, 48],
       [31, 77],
       [57, 10],
       [66, 89],
       [87, 70],
       [47, 33],
       [36, 56],
       [19, 62],
       [61, 84],
       [83, 35],
       [99, 39],
       [72, 63],
       [79, 13],
       [19, 46],
       [14, 33],
       [23, 20],
       [80, 81],
       [13, 87],
       [12, 74],
       [52, 72]], dtype=int32)

In [44]:
arr9.ndim # to check number of dimension of an array

2

In [45]:
arr9.size # to check the size of an array

40

In [46]:
arr9.shape # to check the shape inclusive of both dimension and size

(20, 2)

In [47]:
arr9.dtype # returns datatype of an array

dtype('int32')

## Array Indexing

In [48]:
np.random.seed(101)
ar = np.random.randint(1,10,10)
ar

array([2, 7, 8, 9, 5, 9, 6, 1, 6, 9], dtype=int32)

In [49]:
ar[:4]

array([2, 7, 8, 9], dtype=int32)

In [50]:
ar[-1]

np.int32(9)

In [51]:
ar[5]

np.int32(9)

In [52]:
ar[1]=45
ar

array([ 2, 45,  8,  9,  5,  9,  6,  1,  6,  9], dtype=int32)

## 2-D Array Slicing and Indexing

In [53]:
np.random.seed(100)
arr0 = np.arange(0,25).reshape(5,5)
arr0

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
arr0[0:3,1:3]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [55]:
arr0[0,1]

np.int64(1)

In [56]:
arr0[0:3,1]

array([ 1,  6, 11])

In [57]:
arr0[:3,:3]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [58]:
arr0[2::-1,3::-1]

array([[13, 12, 11, 10],
       [ 8,  7,  6,  5],
       [ 3,  2,  1,  0]])

In [59]:
arr0[2:,3:]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [60]:
arr0[2::2,3::2]

array([[13],
       [23]])

## Shallow Copy and Deep Copy

In [61]:
arr0

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [62]:
# Shallow Copy
ar0 = arr0[2:5,2:5]
ar0

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [63]:
ar0[2,2]=122
ar0

array([[ 12,  13,  14],
       [ 17,  18,  19],
       [ 22,  23, 122]])

In [64]:
arr0 # here ar0 is not a copy of arr0 , it just creates a view and it directs all the changes to the original matrix

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23, 122]])

In [65]:
# Deep Copy
ar1 = arr0[2:5,2:5].copy()
ar1

array([[ 12,  13,  14],
       [ 17,  18,  19],
       [ 22,  23, 122]])

In [66]:
ar1[2,2]=24
ar1

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [67]:
arr0 # here we use .copy() func as to create a copy for the matrix and the changes done in ar1 will not reflect to arr0 and vice-versa 

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23, 122]])

In [68]:
# convert 1:3 matrix in 3:1 matrix using reshape function
arrrr = np.arange(3)
arrrr.reshape(3,1)


array([[0],
       [1],
       [2]])

In [69]:
# convert 1:4 into 2:2 matrix
arrrr = np.arange(16)
reshape = arrrr.reshape(4,4)  #1-D to 2-D
reshape.reshape(1,16)    # conversion of 2-D matrix into 1-D matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [70]:
# returning flat array from 2-D by ravel() func and flatten() func 
ar.ravel?
reshape.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Docstring:
a.ravel([order])

Return a flattened array.

Refer to `numpy.ravel` for full documentation.

See Also
--------
numpy.ravel : equivalent function

ndarray.flat : a flat iterator on the array.
Type:      builtin_function_or_method

In [71]:
# ar.flatten?
flatten = reshape.flatten()

In [72]:
# newaxis keyword instead of reshape can be used
flatten[:,np.newaxis]

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

## Concatenation 

In [73]:
# np.concatenate?

# 1-D array cannot be concated with the 2-D array if u want to do it use .reshape() func or use [[array]] to make it 2-D

In [74]:
np.concatenate([ar0,ar1])  # the elements are added to the row

array([[ 12,  13,  14],
       [ 17,  18,  19],
       [ 22,  23, 122],
       [ 12,  13,  14],
       [ 17,  18,  19],
       [ 22,  23,  24]])

In [75]:
np.concatenate([ar0,ar1],axis=1)  # the elements are added to the column

# axis is to specify row or column

array([[ 12,  13,  14,  12,  13,  14],
       [ 17,  18,  19,  17,  18,  19],
       [ 22,  23, 122,  22,  23,  24]])

In [76]:
ar3=np.array([1,2,3,4,5,6]).reshape(2,3)
ar3

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
ar4=np.array([1,2,3,4,5,6,7,8]).reshape(2,4)
ar4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [78]:
np.concatenate([ar3,ar4],axis=1)

array([[1, 2, 3, 1, 2, 3, 4],
       [4, 5, 6, 5, 6, 7, 8]])

## HStack and VStack

In [79]:
# H-Stack and V-Stack
# np.vstack?
# np.hstack?

In [80]:
x=np.array([[1,2,3],[4,5,6]])
arrrrr = np.array([7,8,9])
ar90 = np.array([[1,2],[3,4]])
ar09 = np.array((1,2,3,4,5))

In [81]:
np.vstack([x,arrrrr])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
np.vstack([arrrrr,x])

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [83]:
np.hstack([x,ar90])

array([[1, 2, 3, 1, 2],
       [4, 5, 6, 3, 4]])

## Split , Vsplit and Hsplit

In [84]:
#np.vsplit?
#np.hsplit?
#np.split?

In [85]:
x
ar89 = np.array((1,2,3,4,5,6))

In [86]:
np.split(ar89,(1,4,5),axis=0) # default split uses vsplit method and 0 is for column and 1 is for row
 # here it returns [:1],[1:4],[4:5],[5:]

[array([1]), array([2, 3, 4]), array([5]), array([6])]

In [87]:
np.vsplit(x,[1,2])

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int64)]

In [88]:
np.hsplit(x,[2,2])
# it return [:1],[1:2],[2:]

[array([[1, 2],
        [4, 5]]),
 array([], shape=(2, 0), dtype=int64),
 array([[3],
        [6]])]

## Universal Functions


In [89]:
ar101 = np.array([[1,2,3],[-4,5,6],[7,-8,9]])
np.sum(ar101)

np.int64(21)

In [90]:
np.sum(ar101,axis=1)

array([6, 7, 8])

In [91]:
np.sum(ar101,axis=0)

array([ 4, -1, 18])

In [92]:
np.std(ar101)

np.float64(5.120763831912405)

In [93]:
np.prod(ar101)

np.int64(362880)

In [94]:
np.var(ar101)

np.float64(26.222222222222218)

In [95]:
np.abs(ar101)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
np.argmax(ar101)

np.int64(8)

In [97]:
np.argmin(ar101)

np.int64(7)

In [98]:
np.argmax(ar101,axis=0)

array([2, 1, 2])

In [99]:
np.argmin(ar101,axis=0)

array([1, 2, 0])

In [100]:
np.argmax(ar101,axis=1)

array([2, 2, 2])

In [101]:
np.argmin(ar101,axis=1)

array([0, 0, 1])

In [102]:
np.median(ar101)

np.float64(3.0)

In [103]:
# np.all?
np.all(ar101,axis=0)

array([ True,  True,  True])

## Broadcasting

## Conditional Arguments

In [104]:
ar401=np.array([1,2,3,4])
ar401

array([1, 2, 3, 4])

In [105]:
ar401>2

array([False, False,  True,  True])

In [106]:
ar401==2

array([False,  True, False, False])

In [107]:
ar401<6

array([ True,  True,  True,  True])

In [108]:
ar401!=9

array([ True,  True,  True,  True])

## NUMPY EXERCISE 1


In [109]:
# import numpy
import numpy as np

In [110]:
# 2.Create an array of 10 zeros
np.zeros((1,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [111]:
# 3.Create an array of 10 ones
np.ones((1,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [112]:
# 4.Create an array of the integers from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [113]:
# 5.Create an array of all the even integers from 10 to 50 
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [114]:
# 6.Create a 3x3 matrix with values ranging from 0 to 8 
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [115]:
# 7. Create a 3x3 identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [116]:
# 8. use NumPy to generate a random number between 0 to 1
np.random.randint(0,2,1)


array([0], dtype=int32)

In [117]:
# 9. Use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution
np.random.standard_normal(25)


array([-0.89325872,  1.7382604 , -1.17970327,  0.08857118, -0.36377559,
       -0.39830003, -0.23471518, -1.43973704,  0.4328165 ,  2.30447259,
       -0.12263538,  0.01545931,  0.26601635, -0.11379467,  1.01106614,
       -1.44077118,  0.98056914,  1.37699631, -0.23028509,  0.48092412,
       -1.26691058,  0.27100509,  2.14076322,  0.47536904,  0.24652489])

In [118]:
# 10. Create a matrix of 10x10 matrix of linearly spaced elements from 0.01 to 1
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [119]:
# 11. Create an array of 20 linearly spaced points between 0 and 1
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [120]:
# 12.Create a 5x5 matrix as  
ar1001 = np.array([[ 1,  2,  3,  4,  5], 
       [ 6,  7,  8,  9, 10], 
       [11, 12, 13, 14, 15], 
       [16, 17, 18, 19, 20], 
       [21, 22, 23, 24, 25]]) 
ar1001

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [121]:
# 12.a find following using slicing 
#  array([[12, 13, 14, 15], 
#         [17, 18, 19, 20], 
#         [22, 23, 24, 25]])
ar1001[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [122]:
# 12.b Find using Slicing - 20
ar1001[3:4,-1]

array([20])

In [123]:
# 12.c   array([[ 2], 
             #  [ 7], 
             #  [12]]) 
ar1001[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [124]:
# 12.d array([21, 22, 23, 24, 25])
ar1001[4]

array([21, 22, 23, 24, 25])

In [125]:
# 12.e array([[16, 17, 18, 19, 20], 
            # [21, 22, 23, 24, 25]])
ar1001[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [126]:
# 13. Get sum of all values in matrix 
np.sum(ar1001)

np.int64(325)

In [127]:
# 14. Get sum of all the columns in matrix
np.sum(ar1001,axis=0)

array([55, 60, 65, 70, 75])

In [128]:
# 15. Get Standard deviation , varience , minimum, maximum from matrix row wise
np.std(ar1001,axis=1)

array([1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356])

In [129]:
np.var(ar1001,axis=1)

array([2., 2., 2., 2., 2.])

In [130]:
np.min(ar1001,axis=1)

array([ 1,  6, 11, 16, 21])

In [131]:
np.max(ar1001,axis=1)

array([ 5, 10, 15, 20, 25])

In [132]:
# 16. create 2 d matrix with all border values nan and other values as 1
a = np.full((6,6),np.nan)
a[1:5,1:5]=1
a


array([[nan, nan, nan, nan, nan, nan],
       [nan,  1.,  1.,  1.,  1., nan],
       [nan,  1.,  1.,  1.,  1., nan],
       [nan,  1.,  1.,  1.,  1., nan],
       [nan,  1.,  1.,  1.,  1., nan],
       [nan, nan, nan, nan, nan, nan]])

## NUMPY EXERCISE 2

In [133]:
# 1. create 1-D , 2-D , 3-D numpy array
ar1=np.array([2,3,4,5])
ar1

array([2, 3, 4, 5])

In [134]:
np.random.seed(1)
ar2=np.arange(0,9).reshape(3,3)
ar2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [135]:
np.random.seed(2)
ar3=np.arange(0,27).reshape(3,3,3)
ar3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [136]:
# 2. Print data type of array.
ar3.dtype

dtype('int64')

In [137]:
# 3. Print shape and dimensions of all the three different array.
ar1.shape 

(4,)

In [138]:
ar2.shape

(3, 3)

In [139]:
ar3.shape

(3, 3, 3)

In [140]:
ar1.ndim

1

In [141]:
ar2.ndim

2

In [142]:
ar3.ndim

3

In [143]:
# 4. Create another 1-D array of 12 elements filled with zero
ar4 = np.zeros(12)
ar4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [144]:
# 5. Create another 2-D array elements filled with ones.
ar5 = np.ones((2,10))
ar5

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [145]:
# 6. Create a 1-D array known as Maths Marks out of 100 having 20 elements.
np.random.seed(102)
Maths_Marks = np.random.randint(0,100,20)
Maths_Marks

array([ 0, 78, 66, 73, 72, 45, 72, 73, 79,  7,  4, 38, 82, 55,  3, 96,  0,
       80, 71, 25], dtype=int32)

In [146]:
# 7. Sort the above array in ascending and descending order.
desc = np.sort(Maths_Marks)[::-1]  # descending order
desc

array([96, 82, 80, 79, 78, 73, 73, 72, 72, 71, 66, 55, 45, 38, 25,  7,  4,
        3,  0,  0], dtype=int32)

In [147]:
asc = np.sort(Maths_Marks)   #ascending order
asc

array([ 0,  0,  3,  4,  7, 25, 38, 45, 55, 66, 71, 72, 72, 73, 73, 78, 79,
       80, 82, 96], dtype=int32)

In [148]:
# 8. Create a copy of sorted array to another variable by deep copying.
copy_dsc = np.copy(desc)
copy_dsc

array([96, 82, 80, 79, 78, 73, 73, 72, 72, 71, 66, 55, 45, 38, 25,  7,  4,
        3,  0,  0], dtype=int32)

In [149]:
# 9. Create 2-D array of 5x5 which is an identity matrix and then convert 1D .
ar10001 = np.eye(5,5)

In [150]:
np.reshape(ar10001,(1,25))

array([[1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 1.]])

In [151]:
# 10. Create 2-D array of 3x3. Add one more row to it.
np.random.seed(10000)
ar201 = np.random.randint(0,9,9).reshape(3,3)
ar201


array([[5, 8, 2],
       [5, 8, 1],
       [6, 8, 5]], dtype=int32)

In [152]:
np.random.seed(10001)
ar202 = np.random.randint(0,9,3)
ar202

array([1, 4, 6], dtype=int32)

In [153]:
ar301 = np.vstack((ar201,ar202))
ar301

array([[5, 8, 2],
       [5, 8, 1],
       [6, 8, 5],
       [1, 4, 6]], dtype=int32)

In [154]:
# 11. Split above array created vertically and horizontally.
#vertically
np.vsplit(ar301,[2,3])
# splitted the array like [:2] i.e [[5,8,2],[5,8,1]] ,
#                    than [2:3] i.e [[6,8,5]],
#                    than [3:] i.e [[1,4,6]]

[array([[5, 8, 2],
        [5, 8, 1]], dtype=int32),
 array([[6, 8, 5]], dtype=int32),
 array([[1, 4, 6]], dtype=int32)]

In [155]:
#horizontally
np.hsplit(ar301,[1,2])

[array([[5],
        [5],
        [6],
        [1]], dtype=int32),
 array([[8],
        [8],
        [8],
        [4]], dtype=int32),
 array([[2],
        [1],
        [5],
        [6]], dtype=int32)]

In [156]:
# 12. Create 4x4 identity matrix. Add 4 to each element.
np.eye(4,4)+4

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [161]:
# 13. Create 1-D array. Initialize with floating point values. Display its ceil, floor and round (with 2 decimal’s). 
ar302 = np.array([1.2,6.5,8.0,7.7,3.4,1.9])
np.ceil(ar302)

array([2., 7., 8., 8., 4., 2.])

In [ ]:
np.floor(ar302)

array([1., 6., 8., 7., 3., 1.])

In [ ]:
np.round(ar302)

array([1., 6., 8., 8., 3., 2.])

In [ ]:
# 14. Create 5x5 matrix. Display min, max, variance and standard deviation column-wise.
ar303 = np.arange(3,28).reshape(5,5)

In [ ]:
# min
np.min(ar303,axis=0)

array([3, 4, 5, 6, 7])

In [ ]:
#max
np.max(ar303,axis=0)

array([23, 24, 25, 26, 27])

In [ ]:
# variance
np.var(ar303,axis=0)

array([50., 50., 50., 50., 50.])

In [ ]:
# standard deviation
np.std(ar303,axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [ ]:
# 15. Create a null vector of size 10 with 6th value filled with 200. 
nv = np.full(10,np.nan)
nv[6]=200
nv


array([ nan,  nan,  nan,  nan,  nan,  nan, 200.,  nan,  nan,  nan])

In [ ]:
# 16. Create a 1-D Array/Vector with values ranging from 100 to 150 in sequence.
vec1 = np.arange(100,151)
vec1

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [ ]:
# 17. Reverse the above vector.
vec1[::-1]

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [ ]:
# 18. Create a 5x5 matrix with values ranging from 0-24 using some function.
np.arange(0,25).reshape(5,5) 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# 19. Find indices of nonzero elements from [1,0,2,0,0,4,0,8]
ar403 = np.array([1,0,2,0,0,4,0,8])
np.nonzero(ar403)[0]

array([0, 2, 5, 7])

In [ ]:
# 20. Create a 10x10 matrix with 1 on the borders and 0 inside.
ar404 = np.full(100,1).reshape(10,10)
ar404[1:9,1:9]=0
ar404

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
# 21. Create 8x8 matrix and fill with 1 and 0 in checkerboard pattern.
mat1 = np.ones((9,9))
mat1[::2,::2]=0
mat1[1::2,1::2]=0
mat1

array([[0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0.]])

In [ ]:
# 22. Create two 3x3 matrix with random integer values. Perform matrix addition, multiplication and subtraction
np.random.seed(1002)
ar405 = np.random.randint(0,9,9).reshape(3,3)
ar405

array([[7, 1, 8],
       [8, 4, 0],
       [5, 5, 2]], dtype=int32)

In [ ]:
np.random.seed(20001)
ar406 = np.random.randint(20,50,9).reshape(3,3)
ar406

array([[25, 29, 26],
       [43, 25, 29],
       [31, 41, 43]], dtype=int32)

In [ ]:
np.sum((ar405,ar406),axis=0)

array([[32, 30, 34],
       [51, 29, 29],
       [36, 46, 45]])

In [ ]:
np.multiply(ar405,ar406)

array([[175,  29, 208],
       [344, 100,   0],
       [155, 205,  86]], dtype=int32)

In [ ]:
np.subtract(ar406,ar405)

array([[18, 28, 18],
       [35, 21, 29],
       [26, 36, 41]], dtype=int32)