In [2]:
import numpy as np

In [3]:
# arange function
arr = np.arange(0,21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [4]:
# zeros function
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
# ones function
arr2 = np.ones(10)
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
# full function
arr3 = np.full(10,3.14)
arr3

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [7]:
# Adding step value
arr = np.arange(0,50,4)
arr


array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [8]:
# adding matrix inside arange using reshape function
arr = np.arange(0,9).reshape(3,3)
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### The difference btwn list and array. 
##### when we are dealing with array we can use only same type of elements where as list can contain any dataype
##### list computation will take more time as array deals with homogeneous data
##### Array is Used only for storing similar datatype

In [9]:
# converting core list to numpy Array
lst = list(range(0,10))        # explicit list creation
l2 = [x for x in range(0,10)]  # list comprehension
l2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
l3 = [str(x) for x in l2]      # converting int to str
l3

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [11]:
l4 = [x**2 for x in l2]        # squaring l2
l4

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [12]:
arr?

Type:        ndarray
String form:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Length:      3
File:        c:\users\vedant gandhi\appdata\local\programs\python\python312\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of create

### Array Library

In [13]:
import array as a
ar = a.array('i',l2) # 'i' is dtype which represents integer
ar1 = a.array('i',[x**2 for x in l2])
ar1

array('i', [0, 1, 4, 9, 16, 25, 36, 49, 64, 81])

In [14]:
nparr = np.array([x+3 for x in l2])
nparr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
# explicitly telling to store dtype as float
nparr1 = np.array([x for x in l2],dtype=float) # same change float to str to make string data type
nparr1 

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [16]:
nparr2 = np.float64([x for x in l2])
nparr2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [17]:
# 2-D lsit or Nested list
l2d = [range(i,i+4) for i in [1,4,5]]
np.array(l2d)

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [18]:
np.zeros([2,2],dtype=int) 

array([[0, 0],
       [0, 0]])

In [19]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((3,2),dtype=str)

array([['1', '1'],
       ['1', '1'],
       ['1', '1']], dtype='<U1')

In [21]:
nparr3 = np.zeros((10,10))
nparr3[1:-1,8:-1]=1
nparr3[1:-1,7:-1]=1
nparr3[1:-1,6:-1]=1
nparr3[1:-1,5:-1]=1
nparr3[1:-1,4:-1]=1
nparr3[1:-1,3:-1]=1
nparr3[1:-1,2:-1]=1
nparr3[1:-1,1:-1]=1
nparr3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
nparr3[1:9,1:9]=1
nparr3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
arr = np.full((3,3),3.14)
arr

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [24]:
arr = np.ones((3,3))
arr[:]=3.14
arr

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [25]:
# eye() function for identity matrix
np.eye?

Signature:
np.eye(
    N,
    M=None,
    k=0,
    dtype=<class 'float'>,
    order='C',
    *,
    device=None,
    like=None,
)
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
    Reference

In [26]:
arr5 = np.eye(7)
arr5

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [27]:
arr7 = np.matrix.transpose(arr5)
arr7

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [30]:
arr8 = np.full((6,6),64)
arr8

array([[64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64]])

### Linspace - Lineraly spaced elements

In [31]:
np.linspace(0,1,5) #starting val , ending val , no. of elements

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [32]:
np.linspace(15,20,20)

array([15.        , 15.26315789, 15.52631579, 15.78947368, 16.05263158,
       16.31578947, 16.57894737, 16.84210526, 17.10526316, 17.36842105,
       17.63157895, 17.89473684, 18.15789474, 18.42105263, 18.68421053,
       18.94736842, 19.21052632, 19.47368421, 19.73684211, 20.        ])

In [35]:
# Random Function - returns value between 0-1
np.random.random((3,3))

array([[0.34995648, 0.21872908, 0.91888093],
       [0.73278122, 0.71814662, 0.95601602],
       [0.05561362, 0.39156453, 0.4799467 ]])

In [36]:
np.random.normal?

Signature: np.random.normal(loc=0.0, scale=1.0, size=None)
Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

.. note::
    New code should use the `~numpy.random.Generator.normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width")

In [37]:
np.random.normal(0,1,10) #values with mean 0 and std 1


array([-0.02501466, -0.2355273 ,  0.61715216,  0.68128756,  0.23705387,
       -1.30061748,  1.18143253,  1.39543398, -0.19559358, -0.07741788])

In [38]:
np.random.normal(0,1,(4,5))

array([[ 0.19843267,  0.72243145, -2.43352447,  1.62946993,  0.00396786],
       [ 1.26000847, -0.44429547, -0.25439262, -0.836161  ,  0.09258439],
       [-0.5660047 ,  1.8685701 , -0.01173944, -0.33376366, -0.34506614],
       [-2.42618182,  1.57051513, -1.01121292, -0.80301518, -1.46286653]])

In [42]:
np.random.randint(50,100,30)

array([59, 79, 76, 57, 56, 83, 51, 58, 74, 89, 83, 73, 76, 96, 95, 62, 75,
       60, 71, 99, 88, 84, 68, 77, 60, 59, 94, 59, 85, 96], dtype=int32)

In [43]:
np.random.randn?


Signature: np.random.randn(*args)
Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned 

### Operations on Numpy Array

In [54]:
arr9 = np.random.randint(10,100,(20,2))
arr9

array([[30, 30],
       [47, 46],
       [76, 90],
       [90, 17],
       [71, 99],
       [73, 23],
       [82, 12],
       [89, 33],
       [45, 65],
       [20, 30],
       [29, 40],
       [74, 71],
       [95, 87],
       [17, 35],
       [80, 85],
       [45, 67],
       [32, 37],
       [92, 67],
       [68, 45],
       [75, 14]], dtype=int32)

In [55]:
arr9.ndim # to check number of dimension of an array

2

In [56]:
arr9.size # to check the size of an array

40

In [57]:
arr9.shape # to check the shape inclusive of both dimension and size

(20, 2)

In [58]:
arr9.dtype # returns datatype of an array

dtype('int32')

### Array Indexing

In [68]:
np.random.seed(101)
ar = np.random.randint(1,10,10)
ar

array([2, 7, 8, 9, 5, 9, 6, 1, 6, 9], dtype=int32)

In [69]:
ar[:4]

array([2, 7, 8, 9], dtype=int32)

In [65]:
ar[-1]

np.int32(9)

In [66]:
ar[5]

np.int32(9)

In [72]:
ar[1]=45
ar

array([ 2, 45,  8,  9,  5,  9,  6,  1,  6,  9], dtype=int32)

## Numpy Assignment

In [78]:
# create 1-D , 2-D , 3-D numpy array
ar1=np.array([2,3,4,5])
ar1

array([2, 3, 4, 5])

In [83]:
np.random.seed(1)
ar2=np.random.randint(1,10,(2,2))
ar2

array([[6, 9],
       [6, 1]], dtype=int32)

In [84]:
np.random.seed(2)
ar3=np.random.randint(20,50,(3,3))
ar3

array([[28, 35, 33],
       [28, 42, 31],
       [38, 31, 28]], dtype=int32)

In [85]:
ar3.dtype

dtype('int32')

In [94]:
ar1.shape 

(4,)

In [91]:
ar2.shape

(2, 2)

In [92]:
ar3.shape

(3, 3)

In [95]:
ar1.ndim

1

In [96]:
ar2.ndim

2

In [97]:
ar3.ndim

2

In [99]:
ar4 = np.zeros(12)
ar4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [105]:
ar5 = np.ones((2,10))
ar5

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [107]:
np.random.seed(102)
Maths_Marks = np.random.randint(0,100,20)
Maths_Marks

array([ 0, 78, 66, 73, 72, 45, 72, 73, 79,  7,  4, 38, 82, 55,  3, 96,  0,
       80, 71, 25], dtype=int32)

In [109]:
np.eye(4,4)+4

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [114]:
ar1[::-1]

array([5, 4, 3, 2])