In [32]:
import numpy as np

In [2]:
# arange function
arr = np.arange(0,21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [3]:
# zeros function
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# ones function
arr2 = np.ones(10)
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
# full function
arr3 = np.full(10,3.14)
arr3

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [6]:
# Adding step value
arr = np.arange(0,50,4)
arr


array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [7]:
# adding matrix inside arange using reshape function
arr = np.arange(0,9).reshape(3,3)
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### The difference btwn list and array. 
##### when we are dealing with array we can use only same type of elements where as list can contain any dataype
##### list computation will take more time as array deals with homogeneous data
##### Array is Used only for storing similar datatype

In [24]:
# converting core list to numpy Array
lst = list(range(0,10))        # explicit list creation
l2 = [x for x in range(0,10)]  # list comprehension
l2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
l3 = [str(x) for x in l2]      # converting int to str
l3

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [23]:
l4 = [x**2 for x in l2]        # squaring l2
l4

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [26]:
arr?

Type:        ndarray
String form:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Length:      3
File:        c:\users\vedant gandhi\appdata\local\programs\python\python312\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of create

### Array Library

In [42]:
import array as a
ar = a.array('i',l2) # 'i' is dtype which represents integer
ar1 = a.array('i',[x**2 for x in l2])
ar1

array('i', [0, 1, 4, 9, 16, 25, 36, 49, 64, 81])

In [47]:
nparr = np.array([x+3 for x in l2])
nparr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [48]:
# explicitly telling to store dtype as float
nparr1 = np.array([x for x in l2],dtype=float) # same change float to str to make string data type
nparr1 

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [50]:
nparr2 = np.float64([x for x in l2])
nparr2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [67]:
# 2-D lsit or Nested list
l2d = [range(i,i+4) for i in [1,4,5]]
np.array(l2d)

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [72]:
np.zeros([2,2],dtype=int) 

array([[0, 0],
       [0, 0]])

In [75]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
np.ones((3,2),dtype=str)

array([['1', '1'],
       ['1', '1'],
       ['1', '1']], dtype='<U1')

In [105]:
nparr3 = np.zeros((10,10))
nparr3[1:-1,8:-1]=1
nparr3[1:-1,7:-1]=1
nparr3[1:-1,6:-1]=1
nparr3[1:-1,5:-1]=1
nparr3[1:-1,4:-1]=1
nparr3[1:-1,3:-1]=1
nparr3[1:-1,2:-1]=1
nparr3[1:-1,1:-1]=1
nparr3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [130]:
nparr3[1:9,1:9]=1
nparr3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [120]:
arr = np.full((3,3),3.14)
arr

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [129]:
arr = np.ones((3,3))
arr[:]=3.14
arr

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [132]:
# eye() function for identity matrix
np.eye?

Signature:
np.eye(
    N,
    M=None,
    k=0,
    dtype=<class 'float'>,
    order='C',
    *,
    device=None,
    like=None,
)
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
    Reference

In [146]:
arr5 = np.eye(7)
arr5

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [148]:
arr7 = np.matrix.transpose(arr5)
arr7

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])