In [9]:
import numpy as np

In [31]:
# arange function
arr = np.arange(0,21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [11]:
# zeros function
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
# ones function
arr2 = np.ones(10)
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
# full function
arr3 = np.full(10,3.14)
arr3

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [32]:
# Adding step value
arr = np.arange(0,50,4)
arr


array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [41]:
# adding matrix inside arange using reshape function
arr = np.arange(0,9).reshape(3,3)
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])