In [2]:
import pandas as pd
pd.__version__

'2.2.2'

## PANDAS - Panel Data
### It has 2 components  : Series-1D array or vector & DataFrame-2D Matrix



### The main difference between pandas series and numpy array is that we can assign different index number as we want like assigning a name or respective numbers in pandas series as well as dataframe too..

### We can assign the index in pandas using .index function

In [3]:
# pd.Series?
s1 = pd.Series([1,14,43],index=['a','b','c'])
s1['b':]

b    14
c    43
dtype: int64

In [4]:
s2 = pd.Series([90,80,99],index=['FDS','Taleau','Calculus'])
s2.values                              # shows every value in the series

array([90, 80, 99])

In [5]:
s2.index                               # shows every indexes in the series


Index(['FDS', 'Taleau', 'Calculus'], dtype='object')

In [6]:
s2.value_counts

<bound method IndexOpsMixin.value_counts of FDS         90
Taleau      80
Calculus    99
dtype: int64>

In [7]:
s3 = pd.Series(['Arpan','Aayush','Vedant'],[99,98,97]) # if u explicitly pass index and data than it will take the respective elements
# s3 = pd.Series(index = ['Arpan','Ayush','Vedant'], data = [99,98,97])
display(s3.values , s3.index , s3)

array(['Arpan', 'Aayush', 'Vedant'], dtype=object)

Index([99, 98, 97], dtype='int64')

99     Arpan
98    Aayush
97    Vedant
dtype: object

In [8]:
# converting numpy array into pandas series
import numpy as np
marks = np.arange(10,30,2)
pdmarks = pd.Series(marks)
print(marks)
print(pdmarks)

[10 12 14 16 18 20 22 24 26 28]
0    10
1    12
2    14
3    16
4    18
5    20
6    22
7    24
8    26
9    28
dtype: int64


In [9]:
# converting dictionary in pandas series
dict = {"Vedant":99,"Aayush":98,"Arpan":97}
pd2dict = pd.Series(dict)
pd2dict

Vedant    99
Aayush    98
Arpan     97
dtype: int64

In [10]:
dict1 ={"Vedant":'A+',"Aayush":'B',"Arpan":'C'}
pd2dict1 = pd.Series(dict1)
pd2dict1

Vedant    A+
Aayush     B
Arpan      C
dtype: object

In [11]:
# converting tuple into pd Series
tup = (1,2,"ABC")
pd2dict1 = pd.Series(tup)
pd2dict1

0      1
1      2
2    ABC
dtype: object

In [12]:
# converting to pd series using list comprehension
lstcomp = [x**2 for x in range(1,20,4)]
lstcomp2pd = pd.Series(index = ["square of 1: ","square of 5: ","square of 9: ","square of 13: ","square of 17:"],data = lstcomp)
lstcomp2pd

square of 1:        1
square of 5:       25
square of 9:       81
square of 13:     169
square of 17:     289
dtype: int64

In [13]:
# pd.DataFrame?

In [14]:
# converting dictionary in pandas dataframe
dict = {"Vedant":[99,34,54],"Aayush":[98,54,32],"Arpan":[97,32,21]}
pd2dict = pd.DataFrame(index=["Maths","FDS","Tableau"],data = dict)
pd2dict

Vedant  Aayush  Arpan
Maths        99      98     97
FDS          34      54     32
Tableau      54      32     21

In [15]:
# u can give column names and index names same as Series
pd.DataFrame([[12,24,36,48],[13,36,49,63]],columns=['sem1','sem2','sem3','sem4'],index=["Maths","FDS"])

sem1  sem2  sem3  sem4
Maths    12    24    36    48
FDS      13    36    49    63

In [16]:
np.random.seed(10)
marks = pd.DataFrame(np.random.randint(0,20,(3,3)),columns=['Vedant','Ayush','Arpan'],index=['FDS','Calculus','Tableau'])
display(marks)
display(marks.columns , marks.values , marks.index)

Vedant  Ayush  Arpan
FDS            9      4     15
Calculus       0     17     16
Tableau       17      8      9

Index(['Vedant', 'Ayush', 'Arpan'], dtype='object')

array([[ 9,  4, 15],
       [ 0, 17, 16],
       [17,  8,  9]], dtype=int32)

Index(['FDS', 'Calculus', 'Tableau'], dtype='object')

In [17]:
marks['Vedant'] # accessing columns

FDS          9
Calculus     0
Tableau     17
Name: Vedant, dtype: int32

In [18]:
# adding a column
marks['Total'] = marks['Vedant']+marks['Ayush']+marks['Arpan']
marks


Vedant  Ayush  Arpan  Total
FDS            9      4     15     28
Calculus       0     17     16     33
Tableau       17      8      9     34

## .loc() , .iloc() , .ix() function
### .loc - only labels can be paced for slicing
### .iloc - only numeric index is being passed
### .ix - both numer index as well as labels can be passed and both can be even passed together

In [19]:
#.loc function
marks.loc['FDS','Arpan'] #it only functions on combination of row and column in argument or when only row is passed

np.int32(15)

In [20]:
marks.loc['FDS']

Vedant     9
Ayush      4
Arpan     15
Total     28
Name: FDS, dtype: int32

In [21]:
marks.loc['FDS','Vedant':'Arpan']

Vedant     9
Ayush      4
Arpan     15
Name: FDS, dtype: int32

In [22]:
marks.loc['Calculus','Ayush':'Arpan']

Ayush    17
Arpan    16
Name: Calculus, dtype: int32

In [23]:
#iloc function - use numerical indexing
marks.iloc[:,3:4]


Total
FDS          28
Calculus     33
Tableau      34

In [24]:
marks[marks['Vedant']<10]

Vedant  Ayush  Arpan  Total
FDS            9      4     15     28
Calculus       0     17     16     33

In [25]:
np.random.seed(10)
ser = pd.Series(np.random.randint(0,10,4))
df = pd.DataFrame(np.random.randint(0,10,(3,4)),columns=['A','B','C','D'])
display(ser,df)

0    9
1    4
2    0
3    1
dtype: int32

A  B  C  D
0  9  0  1  8
1  9  0  8  6
2  4  3  0  4

In [26]:
# Exponential function
display(np.exp(ser),np.exp(df))

0    8103.083928
1      54.598150
2       1.000000
3       2.718282
dtype: float64

A          B            C            D
0  8103.083928   1.000000     2.718282  2980.957987
1  8103.083928   1.000000  2980.957987   403.428793
2    54.598150  20.085537     1.000000    54.598150

In [27]:
# sin function
display(df*np.pi/4,ser*np.pi/4)

A         B         C         D
0  7.068583  0.000000  0.785398  6.283185
1  7.068583  0.000000  6.283185  4.712389
2  3.141593  2.356194  0.000000  3.141593

0    7.068583
1    3.141593
2    0.000000
3    0.785398
dtype: float64

In [28]:
area = pd.Series({'Uttar Pradesh':243286,'Maharashtra':307713,'Bihar':94163},name='area')
pop = pd.Series({"West Bengal":12435425322,"Maharashtra":3143254212,"Bihar":2134144111,},name='pop')
pop_density = area/pop
pop_density

Bihar            0.000044
Maharashtra      0.000098
Uttar Pradesh         NaN
West Bengal           NaN
dtype: float64

In [29]:
area.add(pop,fill_value=0)

Bihar            2.134238e+09
Maharashtra      3.143562e+09
Uttar Pradesh    2.432860e+05
West Bengal      1.243543e+10
dtype: float64

In [30]:
A = pd.Series([2,4,6],index = [0,1,2])
B = pd.Series([1,3,5],index = [1,2,3])
A+B
A.multiply(B,fill_value = 0)

0     0.0
1     4.0
2    18.0
3     0.0
dtype: float64

In [31]:
A = pd.DataFrame(np.random.randint(0,15,(2,2)),columns=list('AB'))
B = pd.DataFrame(np.random.randint(0,10,(3,3)),columns=list('BAC'))
A+B
fill = A.stack().mean()
A.add(B,fill_value=fill)

A     B     C
0  19.0   7.0  13.0
1  11.0  12.0  15.0
2  12.0  14.0  18.0

In [32]:
np.random.seed(11)
A=np.random.randint(10,size=(3,4))
A-A[0]


array([[ 0,  0,  0,  0],
       [-8,  7,  1,  1],
       [-9,  0,  3, -5]], dtype=int32)

In [33]:
df=pd.DataFrame(A,columns=list('QRST'))

## None & Nan as Sentimental Value

### For some dtypes pandas use none as sentimental value , which means that any array containing none must have dtype=object , using none in the array can result in sum when commanded to do summation or any arithemetic operation

### Using np.Nan gives out only Nan irrespective of the arithematic operations so we use np.nanmax() , np.nanmin() , np.nansum()

## Pandas Nullable Dtypes

### The following code just represents that there are nan values or not in an array. If the dtype is 'Int32' than in output the dtype must contain capital I in 'Int32' and if it doesnt have any nan values it will show 'int32'.

In [34]:
pd.Series([1,np.nan,3,pd.NA])

0       1
1     NaN
2       3
3    <NA>
dtype: object

In [35]:
pd.Series([1,2,3,4])

0    1
1    2
2    3
3    4
dtype: int64

## Operation on Null Values:
###  isnull() , notnull() , fillna() , dropna() 

In [36]:
X=pd.Series([1,np.nan])
Y=pd.Series([1,np.nan,pd.NA,np.nan])
pd.isnull(X)

0    False
1     True
dtype: bool

In [37]:
X.dropna()

0    1.0
dtype: float64

In [38]:
pd.notnull(X)

0     True
1    False
dtype: bool

## PANDAS ASSIGNMENT

In [39]:
# 1
prodid = [101,102,103,104,105]
prodname = ['Laptop', 'Mouse' , 'Speaker' , 'Keypad' , 'Pen-drive']
prodprice = [80000,12000,20000,4000,5000,2000]


In [40]:
# 11 
np.random.seed(101)
marks2 = pd.DataFrame(np.random.randint(0,100,(3,3)),index=['Vedant','Ayush','Arpan'],columns=['FDS','Calculus','Python'])
marks2

FDS  Calculus  Python
Vedant   95        11      81
Ayush    70        63      87
Arpan    75         9      77

In [41]:
marks2[marks2.values<40]=41
marks2

FDS  Calculus  Python
Vedant   95        41      81
Ayush    70        63      87
Arpan    75        41      77

In [42]:
# 12
marks2 = marks2+2
marks2[marks2.values>100]=100
marks2

FDS  Calculus  Python
Vedant   97        43      83
Ayush    72        65      89
Arpan    77        43      79

## Assignment - 1/10/2024

In [43]:
data = pd.Series([10,20,30,40,50,60,70,pd.NA,90])
print(data)


0      10
1      20
2      30
3      40
4      50
5      60
6      70
7    <NA>
8      90
dtype: object


In [44]:
# Calculate the sum of the Series
sum = data.sum()
sum


370

In [45]:
# Calculate the mean of the Series
mean = data.mean()
mean


np.float64(46.25)

In [46]:
min = data.min()
min

10

In [47]:
max = data.max()
max

90

In [48]:
is_null = data.isnull()
is_null

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
dtype: bool

In [49]:
not_null = data.notnull()
not_null

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7    False
8     True
dtype: bool

In [50]:
df = pd.DataFrame({'A': [1, 2, None, 4],'B': [5, None, 7, 8]})
df

A    B
0  1.0  5.0
1  2.0  NaN
2  NaN  7.0
3  4.0  8.0

In [51]:
# Dropping columns
dropped_columns = df.dropna(axis=1)
dropped_columns


Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [52]:
# Add a new column
df['C'] = [None, 10, None, 12]
df


A    B     C
0  1.0  5.0   NaN
1  2.0  NaN  10.0
2  NaN  7.0   NaN
3  4.0  8.0  12.0

In [53]:
# Fill missing values in columns using forward fill
forward_fill = df.fillna(method='ffill')
forward_fill


C:\Users\Vedant Gandhi\AppData\Local\Temp\ipykernel_3008\2289157180.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  forward_fill = df.fillna(method='ffill')


A    B     C
0  1.0  5.0   NaN
1  2.0  5.0  10.0
2  2.0  7.0  10.0
3  4.0  8.0  12.0

In [54]:
# Fill missing values in rows using backward-fill
backward_fill = df.fillna(method='bfill')
backward_fill


C:\Users\Vedant Gandhi\AppData\Local\Temp\ipykernel_3008\1016014140.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  backward_fill = df.fillna(method='bfill')


A    B     C
0  1.0  5.0  10.0
1  2.0  7.0  10.0
2  4.0  7.0  12.0
3  4.0  8.0  12.0