In [2]:
import pandas as pd
pd.__version__

'2.2.2'

## PANDAS - Panel Data
### It has 2 components  : Series-1D array or vector & DataFrame-2D Matrix



### The main difference between pandas series and numpy array is that we can assign different index number as we want like assigning a name or respective numbers in pandas series as well as dataframe too..

### We can assign the index in pandas using .index function

In [3]:
# pd.Series?
s1 = pd.Series([1,14,43],index=['a','b','c'])
s1['b':]

b    14
c    43
dtype: int64

In [4]:
s2 = pd.Series([90,80,99],index=['FDS','Taleau','Calculus'])
s2.values                              # shows every value in the series

array([90, 80, 99])

In [5]:
s2.index                               # shows every indexes in the series


Index(['FDS', 'Taleau', 'Calculus'], dtype='object')

In [6]:
s2.value_counts

<bound method IndexOpsMixin.value_counts of FDS         90
Taleau      80
Calculus    99
dtype: int64>

In [7]:
s3 = pd.Series(['Arpan','Aayush','Vedant'],[99,98,97]) # if u explicitly pass index and data than it will take the respective elements
# s3 = pd.Series(index = ['Arpan','Ayush','Vedant'], data = [99,98,97])
display(s3.values , s3.index , s3)

array(['Arpan', 'Aayush', 'Vedant'], dtype=object)

Index([99, 98, 97], dtype='int64')

99     Arpan
98    Aayush
97    Vedant
dtype: object

In [8]:
# converting numpy array into pandas series
import numpy as np
marks = np.arange(10,30,2)
pdmarks = pd.Series(marks)
print(marks)
print(pdmarks)

[10 12 14 16 18 20 22 24 26 28]
0    10
1    12
2    14
3    16
4    18
5    20
6    22
7    24
8    26
9    28
dtype: int64


In [9]:
# converting dictionary in pandas series
dict = {"Vedant":99,"Aayush":98,"Arpan":97}
pd2dict = pd.Series(dict)
pd2dict

Vedant    99
Aayush    98
Arpan     97
dtype: int64

In [10]:
dict1 ={"Vedant":'A+',"Aayush":'B',"Arpan":'C'}
pd2dict1 = pd.Series(dict1)
pd2dict1

Vedant    A+
Aayush     B
Arpan      C
dtype: object

In [11]:
# converting tuple into pd Series
tup = (1,2,"ABC")
pd2dict1 = pd.Series(tup)
pd2dict1

0      1
1      2
2    ABC
dtype: object

In [23]:
# converting to pd series using list comprehension
lstcomp = [x**2 for x in range(1,20,4)]
lstcomp2pd = pd.Series(index = ["square of 1: ","square of 5: ","square of 9: ","square of 13: ","square of 17:"],data = lstcomp)
lstcomp2pd

square of 1:        1
square of 5:       25
square of 9:       81
square of 13:     169
square of 17:     289
dtype: int64

In [13]:
# pd.DataFrame?

In [24]:
# converting dictionary in pandas dataframe
dict = {"Vedant":[99,34,54],"Aayush":[98,54,32],"Arpan":[97,32,21]}
pd2dict = pd.DataFrame(index=["Maths","FDS","Tableau"],data = dict)
pd2dict

Vedant  Aayush  Arpan
Maths        99      98     97
FDS          34      54     32
Tableau      54      32     21

In [26]:
# u can give column names and index names same as Series
pd.DataFrame([[12,24,36,48],[13,36,49,63]],columns=['sem1','sem2','sem3','sem4'],index=["Maths","FDS"])

sem1  sem2  sem3  sem4
Maths    12    24    36    48
FDS      13    36    49    63

In [42]:
np.random.seed(10)
marks = pd.DataFrame(np.random.randint(0,20,(3,3)),columns=['Vedant','Ayush','Arpan'],index=['FDS','Calculus','Tableau'])
display(marks)
display(marks.columns , marks.values , marks.index)

Vedant  Ayush  Arpan
FDS            9      4     15
Calculus       0     17     16
Tableau       17      8      9

Index(['Vedant', 'Ayush', 'Arpan'], dtype='object')

array([[ 9,  4, 15],
       [ 0, 17, 16],
       [17,  8,  9]], dtype=int32)

Index(['FDS', 'Calculus', 'Tableau'], dtype='object')

In [43]:
marks['Vedant'] # accessing columns

FDS          9
Calculus     0
Tableau     17
Name: Vedant, dtype: int32

In [49]:
# adding a column
marks['Total'] = marks['Vedant']+marks['Ayush']+marks['Arpan']
marks


Vedant  Ayush  Arpan  Total
FDS            9      4     15     28
Calculus       0     17     16     33
Tableau       17      8      9     34

## .loc() , .iloc() , .ix() function
### .loc - only labels can be paced for slicing
### .iloc - only numeric index is being passed
### .ix - both numer index as well as labels can be passed and both can be even passed together

In [71]:
#.loc function
marks.loc['FDS','Arpan'] #it only functions on combination of row and column in argument or when only row is passed

np.int32(15)

In [72]:
marks.loc['FDS']

Vedant     9
Ayush      4
Arpan     15
Total     28
Name: FDS, dtype: int32

In [80]:
marks.loc['FDS','Vedant':'Arpan']

Vedant     9
Ayush      4
Arpan     15
Name: FDS, dtype: int32

In [81]:
marks.loc['Calculus','Ayush':'Arpan']

Ayush    17
Arpan    16
Name: Calculus, dtype: int32

In [89]:
#iloc function - use numerical indexing
marks.iloc[:,3:4]


Total
FDS          28
Calculus     33
Tableau      34

In [98]:
marks[marks['Vedant']<10]

Vedant  Ayush  Arpan  Total
FDS            9      4     15     28
Calculus       0     17     16     33

## PANDAS ASSIGNMENT

In [ ]:
# 1
prodid = [101,102,103,104,105]
prodname = ['Laptop', 'Mouse' , 'Speaker' , 'Keypad' , 'Pen-drive']
prodprice = [80000,12000,20000,4000,5000,2000]


In [135]:
# 11 
np.random.seed(101)
marks2 = pd.DataFrame(np.random.randint(0,100,(3,3)),index=['Vedant','Ayush','Arpan'],columns=['FDS','Calculus','Python'])
marks2

FDS  Calculus  Python
Vedant   95        11      81
Ayush    70        63      87
Arpan    75         9      77

In [136]:
marks2[marks2.values<40]=41
marks2

FDS  Calculus  Python
Vedant   95        41      81
Ayush    70        63      87
Arpan    75        41      77

In [138]:
# 12
marks2 = marks2+2
marks2[marks2.values>100]=100
marks2

FDS  Calculus  Python
Vedant   97        43      83
Ayush    72        65      89
Arpan    77        43      79

In [141]:
# 13
marks2[marks[:,1:2]>50]

InvalidIndexError: (slice(None, None, None), slice(1, 2, None))

In [125]:
# 14 calculate total and percentile for all the students
marks2['Total']=marks2['FDS']+marks2['Calculus']+marks2['']
marks2['Percentile'] = (marks2['Total']*100)/300
marks2

KeyError: ''